name: nerf_synthetic
path: data/nerf_synthetic
dataset_module: lib.datasets.nerf_synthetic

scene: lego

init_rays_num: 1024

train_dataset:
  split: train
  view: 0
  input_ratio: 1.

test_dataset:
  split: test
  view: 0
  input_ratio: .5
