app_name: triton-ngp
header: '${hydra.help.app_name} is powered by Hydra.
  '
footer: 'Powered by Hydra (https://hydra.cc)

  Use --hydra-help to view Hydra specific help
  '
template: '${hydra.help.header}

  == Configuration groups ==

  Compose your configuration from those groups (group=option)


  $APP_CONFIG_GROUPS


  == Config ==

  Override anything in the config (foo.bar=value)


  $CONFIG


  ${hydra.help.footer}
  '
